// scripts/seedFinanceDataFull.js
// Idempotent seeder for Earnings: July -> Dec 2024 + mock old doc + 2 pending demo items
// Usage: node scripts/seedFinanceDataFull.js
const mongoose = require("mongoose");
require("dotenv").config();
const bcrypt = require('bcryptjs');

const Earning = require("../models/Earning");
const User = require("../models/User");

const SALT_ROUNDS = 10;

const randPassword = () =>
  Math.random().toString(36).slice(-10) + Math.random().toString(36).slice(-4);

/**
 * Upsert documents by a small deterministic filter to avoid duplicates.
 * The filter uses date + (name || description) + earnings/expenses where present.
 */
const upsertDocs = async (arr) => {
  for (const doc of arr) {
    const filter = {
      date: doc.date,
    };

    if (doc.name) filter.name = doc.name;
    else if (doc.description) filter.description = doc.description;

    // include amounts if provided to be more precise
    if (typeof doc.earnings !== "undefined") filter.earnings = doc.earnings;
    if (typeof doc.expenses !== "undefined") filter.expenses = doc.expenses;

    // remove undefined fields (safety)
    Object.keys(filter).forEach((k) => {
      if (filter[k] === undefined || filter[k] === null) delete filter[k];
    });

    await Earning.findOneAndUpdate(filter, doc, {
      upsert: true,
      new: true,
      setDefaultsOnInsert: true,
    });
  }
};

const ensureAdminUser = async () => {
  let adminUser = await User.findOne({ role: "admin" });
  if (adminUser) {
    console.log("Found admin user:", adminUser.email);
    return adminUser;
  }

  // fallback to chairman if admin not present
  const fallback = await User.findOne({ role: "chairman" });
  if (fallback) {
    console.log("No admin found — using chairman as adminUser:", fallback.email);
    return fallback;
  }

  // create a seed admin user
  const password = randPassword();
  const hashed = await bcrypt.hash(password, SALT_ROUNDS);
  const email = "admin@example.com";
  const name = "Seed Admin";

  const newUser = new User({
    name,
    email,
    password: hashed,
    role: "admin",
    status: "approved",
    // optional uniqueId for users as you discussed earlier
    uniqueId: "ADM0001",
  });

  await newUser.save();
  console.log("Created seed admin:", email, "password:", password);
  return newUser;
};

const seedFinanceData = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI, {
      serverSelectionTimeoutMS: 30000,
      socketTimeoutMS: 30000,
    });
    console.log("Connected to MongoDB for seeding");

    const adminUser = await ensureAdminUser();
    const adminId = adminUser._id;

    // ===== JULY 2024 =====
    const julyRevenue = [
      {
        date: new Date("2024-07-05"),
        month: "July 2024",
        earnings: 30000,
        expenses: 0,
        description: "Q3 school fee collected",
        type: "revenue",
        requestType: "school fee",
        name: "Q3 School Fee Collection",
        time: "10:00 AM",
        modeOfPayment: "upi",
        feePeriod: "Q3 2024",
        studentUniqueId: "STU2024011",
        status: "approved",
        requestedBy: adminId,
        reviewedBy: adminId,
        reviewedAt: new Date("2024-07-05"),
        reviewNotes: "Regular fee payment approved",
      },
      {
        date: new Date("2024-07-10"),
        month: "July 2024",
        earnings: 18000,
        expenses: 0,
        description: "Summer hostel fee",
        type: "revenue",
        requestType: "hostel fee",
        name: "Summer Term Hostel Fee",
        time: "11:30 AM",
        modeOfPayment: "bank transfer",
        feePeriod: "Summer 2024",
        studentUniqueId: "STU2024012",
        status: "approved",
        requestedBy: adminId,
        reviewedBy: adminId,
        reviewedAt: new Date("2024-07-10"),
      },
      {
        date: new Date("2024-07-15"),
        month: "July 2024",
        earnings: 12000,
        expenses: 0,
        description: "Sports uniform fee",
        type: "revenue",
        requestType: "uniform fee",
        name: "Sports Uniform Fee",
        time: "02:00 PM",
        modeOfPayment: "cash",
        feePeriod: "2024",
        studentUniqueId: "STU2024013",
        status: "approved",
        requestedBy: adminId,
      },
      {
        date: new Date("2024-07-20"),
        month: "July 2024",
        earnings: 75000,
        expenses: 0,
        description: "Alumni donation for library",
        type: "revenue",
        requestType: "donation",
        name: "Alumni Association Donation",
        time: "04:00 PM",
        modeOfPayment: "cheque",
        status: "approved",
        requestedBy: adminId,
        reviewedBy: adminId,
        reviewedAt: new Date("2024-07-20"),
        reviewNotes: "Donation for library expansion",
      },
      {
        date: new Date("2024-07-25"),
        month: "July 2024",
        earnings: 5000,
        expenses: 0,
        description: "Activity and lab fees",
        type: "revenue",
        requestType: "other fees",
        name: "Lab & Activity Fees",
        time: "01:30 PM",
        modeOfPayment: "upi",
        feePeriod: "July 2024",
        studentUniqueId: "STU2024014",
        status: "approved",
        requestedBy: adminId,
      },
    ];

    const julyExpenses = [
      {
        date: new Date("2024-07-01"),
        month: "July 2024",
        earnings: 0,
        expenses: 50000,
        description: "July teaching staff salaries",
        type: "expense",
        requestType: "salary",
        name: "July Staff Salaries",
        time: "09:00 AM",
        modeOfPayment: "bank transfer",
        status: "approved",
        requestedBy: adminId,
        reviewedBy: adminId,
        reviewedAt: new Date("2024-07-01"),
        reviewNotes: "Monthly salary payment",
      },
      {
        date: new Date("2024-07-08"),
        month: "July 2024",
        earnings: 0,
        expenses: 6500,
        description: "Bus maintenance and fuel",
        type: "expense",
        requestType: "transport",
        name: "Transport Expenses",
        time: "03:00 PM",
        modeOfPayment: "cash",
        status: "approved",
        requestedBy: adminId,
        reviewedBy: adminId,
        reviewedAt: new Date("2024-07-08"),
      },
      {
        date: new Date("2024-07-12"),
        month: "July 2024",
        earnings: 0,
        expenses: 15000,
        description: "Canteen supplies for July",
        type: "expense",
        requestType: "food",
        name: "Food Supplies",
        time: "10:30 AM",
        modeOfPayment: "upi",
        status: "approved",
        requestedBy: adminId,
      },
      {
        date: new Date("2024-07-18"),
        month: "July 2024",
        earnings: 0,
        expenses: 4000,
        description: "Books and stationary supplies",
        type: "expense",
        requestType: "stationary",
        name: "Stationary Purchase",
        time: "11:45 AM",
        modeOfPayment: "card",
        status: "approved",
        requestedBy: adminId,
      },
      {
        date: new Date("2024-07-22"),
        month: "July 2024",
        earnings: 0,
        expenses: 7000,
        description: "Cleaning and sanitation supplies",
        type: "expense",
        requestType: "housekeeping",
        name: "Housekeeping Supplies",
        time: "02:15 PM",
        modeOfPayment: "cash",
        status: "approved",
        requestedBy: adminId,
      },
      {
        date: new Date("2024-07-28"),
        month: "July 2024",
        earnings: 0,
        expenses: 10000,
        description: "Office equipment and furniture",
        type: "expense",
        requestType: "admin office",
        name: "Office Equipment",
        time: "04:30 PM",
        modeOfPayment: "bank transfer",
        status: "approved",
        requestedBy: adminId,
      },
    ];

    // ===== AUGUST 2024 =====
    const augustRevenue = [
      {
        date: new Date("2024-08-02"),
        month: "August 2024",
        earnings: 35000,
        expenses: 0,
        description: "School fee for new term",
        type: "revenue",
        requestType: "school fee",
        name: "New Term Fee Collection",
        time: "09:30 AM",
        modeOfPayment: "bank transfer",
        feePeriod: "Q3 2024",
        studentUniqueId: "STU2024021",
        status: "approved",
        requestedBy: adminId,
        reviewedBy: adminId,
        reviewedAt: new Date("2024-08-02"),
      },
      {
        date: new Date("2024-08-08"),
        month: "August 2024",
        earnings: 20000,
        expenses: 0,
        description: "Hostel accommodation fee",
        type: "revenue",
        requestType: "hostel fee",
        name: "August Hostel Fee",
        time: "01:00 PM",
        modeOfPayment: "upi",
        feePeriod: "August 2024",
        studentUniqueId: "STU2024022",
        status: "approved",
        requestedBy: adminId,
      },
      {
        date: new Date("2024-08-12"),
        month: "August 2024",
        earnings: 150000,
        expenses: 0,
        description: "Government infrastructure grant",
        type: "revenue",
        requestType: "grant",
        name: "Infrastructure Development Grant",
        time: "10:00 AM",
        modeOfPayment: "bank transfer",
        status: "approved",
        requestedBy: adminId,
        reviewedBy: adminId,
        reviewedAt: new Date("2024-08-12"),
        reviewNotes: "Grant for building renovation",
      },
      {
        date: new Date("2024-08-18"),
        month: "August 2024",
        earnings: 8500,
        expenses: 0,
        description: "Exam and registration fees",
        type: "revenue",
        requestType: "other fees",
        name: "Exam Fees",
        time: "03:30 PM",
        modeOfPayment: "card",
        feePeriod: "August 2024",
        studentUniqueId: "STU2024023",
        status: "approved",
        requestedBy: adminId,
      },
      {
        date: new Date("2024-08-25"),
        month: "August 2024",
        earnings: 25000,
        expenses: 0,
        description: "Corporate CSR donation",
        type: "revenue",
        requestType: "donation",
        name: "XYZ Corp CSR Initiative",
        time: "11:00 AM",
        modeOfPayment: "cheque",
        status: "approved",
        requestedBy: adminId,
        reviewedBy: adminId,
        reviewedAt: new Date("2024-08-25"),
      },
    ];

    const augustExpenses = [
      {
        date: new Date("2024-08-01"),
        month: "August 2024",
        earnings: 0,
        expenses: 52000,
        description: "August teaching staff salaries",
        type: "expense",
        requestType: "salary",
        name: "August Staff Salaries",
        time: "09:00 AM",
        modeOfPayment: "bank transfer",
        status: "approved",
        requestedBy: adminId,
        reviewedBy: adminId,
        reviewedAt: new Date("2024-08-01"),
      },
      {
        date: new Date("2024-08-05"),
        month: "August 2024",
        earnings: 0,
        expenses: 8000,
        description: "Transport vehicle servicing",
        type: "expense",
        requestType: "transport",
        name: "Vehicle Servicing",
        time: "02:00 PM",
        modeOfPayment: "cash",
        status: "approved",
        requestedBy: adminId,
      },
      {
        date: new Date("2024-08-10"),
        month: "August 2024",
        earnings: 0,
        expenses: 18000,
        description: "Canteen supplies and groceries",
        type: "expense",
        requestType: "food",
        name: "Monthly Food Supplies",
        time: "11:00 AM",
        modeOfPayment: "upi",
        status: "approved",
        requestedBy: adminId,
        reviewedBy: adminId,
        reviewedAt: new Date("2024-08-10"),
      },
      {
        date: new Date("2024-08-15"),
        month: "August 2024",
        earnings: 0,
        expenses: 5500,
        description: "School supplies and books",
        type: "expense",
        requestType: "stationary",
        name: "Stationary & Books",
        time: "10:30 AM",
        modeOfPayment: "card",
        status: "approved",
        requestedBy: adminId,
      },
      {
        date: new Date("2024-08-20"),
        month: "August 2024",
        earnings: 0,
        expenses: 9000,
        description: "Cleaning and maintenance services",
        type: "expense",
        requestType: "housekeeping",
        name: "Housekeeping Services",
        time: "03:45 PM",
        modeOfPayment: "bank transfer",
        status: "approved",
        requestedBy: adminId,
      },
      {
        date: new Date("2024-08-22"),
        month: "August 2024",
        earnings: 0,
        expenses: 12000,
        description: "Office software and admin tools",
        type: "expense",
        requestType: "admin office",
        name: "Software Licenses",
        time: "01:15 PM",
        modeOfPayment: "bank transfer",
        status: "approved",
        requestedBy: adminId,
      },
      {
        date: new Date("2024-08-28"),
        month: "August 2024",
        earnings: 0,
        expenses: 30000,
        description: "Electrical work and repairs",
        type: "expense",
        requestType: "other",
        name: "Electrical Maintenance",
        time: "04:00 PM",
        modeOfPayment: "cheque",
        status: "approved",
        requestedBy: adminId,
      },
    ];

    // ===== SEPTEMBER 2024 =====
    const septemberRevenue = [
      {
        date: new Date("2024-09-03"),
        month: "September 2024",
        earnings: 40000,
        expenses: 0,
        description: "Quarterly school fee",
        type: "revenue",
        requestType: "school fee",
        name: "Q3 Fee Collection",
        time: "10:30 AM",
        modeOfPayment: "bank transfer",
        feePeriod: "Q3 2024",
        studentUniqueId: "STU2024031",
        status: "approved",
        requestedBy: adminId,
        reviewedBy: adminId,
        reviewedAt: new Date("2024-09-03"),
      },
      {
        date: new Date("2024-09-09"),
        month: "September 2024",
        earnings: 22000,
        expenses: 0,
        description: "Hostel fee for autumn term",
        type: "revenue",
        requestType: "hostel fee",
        name: "Autumn Hostel Fee",
        time: "02:00 PM",
        modeOfPayment: "upi",
        feePeriod: "Autumn 2024",
        studentUniqueId: "STU2024032",
        status: "approved",
        requestedBy: adminId,
      },
      {
        date: new Date("2024-09-14"),
        month: "September 2024",
        earnings: 9500,
        expenses: 0,
        description: "Winter uniform fee",
        type: "revenue",
        requestType: "uniform fee",
        name: "Winter Uniform Fee",
        time: "11:00 AM",
        modeOfPayment: "card",
        feePeriod: "2024",
        studentUniqueId: "STU2024033",
        status: "approved",
        requestedBy: adminId,
      },
      {
        date: new Date("2024-09-20"),
        month: "September 2024",
        earnings: 6000,
        expenses: 0,
        description: "Library and computer lab fees",
        type: "revenue",
        requestType: "other fees",
        name: "Library & Lab Fees",
        time: "03:15 PM",
        modeOfPayment: "upi",
        feePeriod: "September 2024",
        studentUniqueId: "STU2024034",
        status: "approved",
        requestedBy: adminId,
      },
      {
        date: new Date("2024-09-26"),
        month: "September 2024",
        earnings: 100000,
        expenses: 0,
        description: "State education development grant",
        type: "revenue",
        requestType: "grant",
        name: "Education Development Grant",
        time: "09:00 AM",
        modeOfPayment: "bank transfer",
        status: "approved",
        requestedBy: adminId,
        reviewedBy: adminId,
        reviewedAt: new Date("2024-09-26"),
        reviewNotes: "Government grant approved",
      },
    ];

    const septemberExpenses = [
      {
        date: new Date("2024-09-01"),
        month: "September 2024",
        earnings: 0,
        expenses: 53000,
        description: "September staff salaries",
        type: "expense",
        requestType: "salary",
        name: "September Staff Salaries",
        time: "09:00 AM",
        modeOfPayment: "bank transfer",
        status: "approved",
        requestedBy: adminId,
        reviewedBy: adminId,
        reviewedAt: new Date("2024-09-01"),
      },
      {
        date: new Date("2024-09-06"),
        month: "September 2024",
        earnings: 0,
        expenses: 7200,
        description: "Transport fuel and minor repairs",
        type: "expense",
        requestType: "transport",
        name: "Transport Maintenance",
        time: "01:30 PM",
        modeOfPayment: "cash",
        status: "approved",
        requestedBy: adminId,
      },
      {
        date: new Date("2024-09-11"),
        month: "September 2024",
        earnings: 0,
        expenses: 16500,
        description: "Canteen groceries and supplies",
        type: "expense",
        requestType: "food",
        name: "Food Supplies",
        time: "10:00 AM",
        modeOfPayment: "upi",
        status: "approved",
        requestedBy: adminId,
      },
      {
        date: new Date("2024-09-17"),
        month: "September 2024",
        earnings: 0,
        expenses: 4800,
        description: "Textbooks and teaching materials",
        type: "expense",
        requestType: "stationary",
        name: "Teaching Materials",
        time: "02:45 PM",
        modeOfPayment: "card",
        status: "approved",
        requestedBy: adminId,
      },
      {
        date: new Date("2024-09-23"),
        month: "September 2024",
        earnings: 0,
        expenses: 8500,
        description: "Cleaning services and supplies",
        type: "expense",
        requestType: "housekeeping",
        name: "Housekeeping Services",
        time: "11:30 AM",
        modeOfPayment: "bank transfer",
        status: "approved",
        requestedBy: adminId,
      },
      {
        date: new Date("2024-09-28"),
        month: "September 2024",
        earnings: 0,
        expenses: 15000,
        description: "Computer lab equipment upgrade",
        type: "expense",
        requestType: "admin office",
        name: "IT Equipment",
        time: "04:00 PM",
        modeOfPayment: "bank transfer",
        status: "approved",
        requestedBy: adminId,
      },
    ];

    // ===== OCTOBER 2024 =====
    const octoberRevenue = [
      {
        date: new Date("2024-10-04"),
        month: "October 2024",
        earnings: 42000,
        expenses: 0,
        description: "Mid-term school fee",
        type: "revenue",
        requestType: "school fee",
        name: "Mid-Term Fee Collection",
        time: "10:00 AM",
        modeOfPayment: "upi",
        feePeriod: "Q4 2024",
        studentUniqueId: "STU2024041",
        status: "approved",
        requestedBy: adminId,
        reviewedBy: adminId,
        reviewedAt: new Date("2024-10-04"),
      },
      {
        date: new Date("2024-10-10"),
        month: "October 2024",
        earnings: 19000,
        expenses: 0,
        description: "October hostel charges",
        type: "revenue",
        requestType: "hostel fee",
        name: "October Hostel Fee",
        time: "01:45 PM",
        modeOfPayment: "bank transfer",
        feePeriod: "October 2024",
        studentUniqueId: "STU2024042",
        status: "approved",
        requestedBy: adminId,
      },
      {
        date: new Date("2024-10-15"),
        month: "October 2024",
        earnings: 50000,
        expenses: 0,
        description: "Local business donation",
        type: "revenue",
        requestType: "donation",
        name: "Community Business Donation",
        time: "03:00 PM",
        modeOfPayment: "cheque",
        status: "approved",
        requestedBy: adminId,
        reviewedBy: adminId,
        reviewedAt: new Date("2024-10-15"),
      },
      {
        date: new Date("2024-10-21"),
        month: "October 2024",
        earnings: 7500,
        expenses: 0,
        description: "Sports and cultural fees",
        type: "revenue",
        requestType: "other fees",
        name: "Sports & Cultural Fees",
        time: "11:30 AM",
        modeOfPayment: "card",
        feePeriod: "October 2024",
        studentUniqueId: "STU2024043",
        status: "approved",
        requestedBy: adminId,
      },
      {
        date: new Date("2024-10-28"),
        month: "October 2024",
        earnings: 10000,
        expenses: 0,
        description: "Annual day event fees",
        type: "revenue",
        requestType: "other fees",
        name: "Annual Day Fees",
        time: "09:30 AM",
        modeOfPayment: "upi",
        feePeriod: "October 2024",
        studentUniqueId: "STU2024044",
        status: "approved",
        requestedBy: adminId,
      },
    ];

    const octoberExpenses = [
      {
        date: new Date("2024-10-01"),
        month: "October 2024",
        earnings: 0,
        expenses: 54000,
        description: "October staff salaries",
        type: "expense",
        requestType: "salary",
        name: "October Staff Salaries",
        time: "09:00 AM",
        modeOfPayment: "bank transfer",
        status: "approved",
        requestedBy: adminId,
        reviewedBy: adminId,
        reviewedAt: new Date("2024-10-01"),
      },
      {
        date: new Date("2024-10-07"),
        month: "October 2024",
        earnings: 0,
        expenses: 6800,
        description: "Bus fuel and maintenance",
        type: "expense",
        requestType: "transport",
        name: "Transport Expenses",
        time: "02:30 PM",
        modeOfPayment: "cash",
        status: "approved",
        requestedBy: adminId,
      },
      {
        date: new Date("2024-10-12"),
        month: "October 2024",
        earnings: 0,
        expenses: 17000,
        description: "Canteen monthly supplies",
        type: "expense",
        requestType: "food",
        name: "Food Supplies",
        time: "11:00 AM",
        modeOfPayment: "upi",
        status: "approved",
        requestedBy: adminId,
      },
      {
        date: new Date("2024-10-16"),
        month: "October 2024",
        earnings: 0,
        expenses: 5200,
        description: "Office supplies and stationery",
        type: "expense",
        requestType: "stationary",
        name: "Office Supplies",
        time: "03:15 PM",
        modeOfPayment: "card",
        status: "approved",
        requestedBy: adminId,
      },
      {
        date: new Date("2024-10-22"),
        month: "October 2024",
        earnings: 0,
        expenses: 9500,
        description: "Deep cleaning and sanitation",
        type: "expense",
        requestType: "housekeeping",
        name: "Deep Cleaning Services",
        time: "10:30 AM",
        modeOfPayment: "bank transfer",
        status: "approved",
        requestedBy: adminId,
      },
      {
        date: new Date("2024-10-25"),
        month: "October 2024",
        earnings: 0,
        expenses: 20000,
        description: "Annual day event arrangements",
        type: "expense",
        requestType: "other",
        name: "Annual Day Event",
        time: "01:00 PM",
        modeOfPayment: "bank transfer",
        status: "approved",
        requestedBy: adminId,
      },
      {
        date: new Date("2024-10-30"),
        month: "October 2024",
        earnings: 0,
        expenses: 11000,
        description: "Network and system maintenance",
        type: "expense",
        requestType: "admin office",
        name: "IT Maintenance",
        time: "04:30 PM",
        modeOfPayment: "bank transfer",
        status: "approved",
        requestedBy: adminId,
      },
    ];

    // ===== NOVEMBER 2024 =====
    const novemberRevenue = [
      {
        date: new Date("2024-11-05"),
        month: "November 2024",
        earnings: 38000,
        expenses: 0,
        description: "November term fee",
        type: "revenue",
        requestType: "school fee",
        name: "November Fee Collection",
        time: "09:45 AM",
        modeOfPayment: "bank transfer",
        feePeriod: "Q4 2024",
        studentUniqueId: "STU2024051",
        status: "approved",
        requestedBy: adminId,
        reviewedBy: adminId,
        reviewedAt: new Date("2024-11-05"),
      },
      {
        date: new Date("2024-11-11"),
        month: "November 2024",
        earnings: 21000,
        expenses: 0,
        description: "November hostel fee",
        type: "revenue",
        requestType: "hostel fee",
        name: "November Hostel Fee",
        time: "02:30 PM",
        modeOfPayment: "upi",
        feePeriod: "November 2024",
        studentUniqueId: "STU2024052",
        status: "approved",
        requestedBy: adminId,
      },
      {
        date: new Date("2024-11-16"),
        month: "November 2024",
        earnings: 120000,
        expenses: 0,
        description: "Year-end government grant",
        type: "revenue",
        requestType: "grant",
        name: "Year-End Education Grant",
        time: "10:00 AM",
        modeOfPayment: "bank transfer",
        status: "approved",
        requestedBy: adminId,
        reviewedBy: adminId,
        reviewedAt: new Date("2024-11-16"),
        reviewNotes: "Annual grant disbursement",
      },
      {
        date: new Date("2024-11-20"),
        month: "November 2024",
        earnings: 60000,
        expenses: 0,
        description: "Parent association fundraiser",
        type: "revenue",
        requestType: "donation",
        name: "Parent Fundraiser Donation",
        time: "04:00 PM",
        modeOfPayment: "cheque",
        status: "approved",
        requestedBy: adminId,
        reviewedBy: adminId,
        reviewedAt: new Date("2024-11-20"),
      },
      {
        date: new Date("2024-11-25"),
        month: "November 2024",
        earnings: 8000,
        expenses: 0,
        description: "Final exam registration fees",
        type: "revenue",
        requestType: "other fees",
        name: "Final Exam Fees",
        time: "11:15 AM",
        modeOfPayment: "upi",
        feePeriod: "November 2024",
        studentUniqueId: "STU2024053",
        status: "approved",
        requestedBy: adminId,
      },
    ];

    const novemberExpenses = [
      {
        date: new Date("2024-11-01"),
        month: "November 2024",
        earnings: 0,
        expenses: 55000,
        description: "November staff salaries",
        type: "expense",
        requestType: "salary",
        name: "November Staff Salaries",
        time: "09:00 AM",
        modeOfPayment: "bank transfer",
        status: "approved",
        requestedBy: adminId,
        reviewedBy: adminId,
        reviewedAt: new Date("2024-11-01"),
      },
      {
        date: new Date("2024-11-06"),
        month: "November 2024",
        earnings: 0,
        expenses: 7500,
        description: "Transport vehicle repairs",
        type: "expense",
        requestType: "transport",
        name: "Vehicle Repairs",
        time: "01:00 PM",
        modeOfPayment: "cash",
        status: "approved",
        requestedBy: adminId,
      },
      {
        date: new Date("2024-11-10"),
        month: "November 2024",
        earnings: 0,
        expenses: 18500,
        description: "Canteen supplies and groceries",
        type: "expense",
        requestType: "food",
        name: "Monthly Food Supplies",
        time: "10:30 AM",
        modeOfPayment: "upi",
        status: "approved",
        requestedBy: adminId,
      },
      {
        date: new Date("2024-11-14"),
        month: "November 2024",
        earnings: 0,
        expenses: 6000,
        description: "Exam papers and stationery",
        type: "expense",
        requestType: "stationary",
        name: "Exam Materials",
        time: "02:00 PM",
        modeOfPayment: "card",
        status: "approved",
        requestedBy: adminId,
      },
      {
        date: new Date("2024-11-19"),
        month: "November 2024",
        earnings: 0,
        expenses: 8800,
        description: "Monthly cleaning services",
        type: "expense",
        requestType: "housekeeping",
        name: "Housekeeping Services",
        time: "11:45 AM",
        modeOfPayment: "bank transfer",
        status: "approved",
        requestedBy: adminId,
      },
      {
        date: new Date("2024-11-23"),
        month: "November 2024",
        earnings: 0,
        expenses: 13500,
        description: "Admin office upgrades",
        type: "expense",
        requestType: "admin office",
        name: "Office Upgrades",
        time: "03:30 PM",
        modeOfPayment: "bank transfer",
        status: "approved",
        requestedBy: adminId,
      },
      {
        date: new Date("2024-11-27"),
        month: "November 2024",
        earnings: 0,
        expenses: 25000,
        description: "Building winterization and repairs",
        type: "expense",
        requestType: "other",
        name: "Winter Preparation",
        time: "09:30 AM",
        modeOfPayment: "cheque",
        status: "pending",
        requestedBy: adminId,
      },
    ];

    // ===== DECEMBER 2024 =====
    const decemberRevenue = [
      {
        date: new Date("2024-12-05"),
        month: "December 2024",
        earnings: 45000,
        expenses: 0,
        description: "December fee collection",
        type: "revenue",
        requestType: "school fee",
        name: "December Fee Collection",
        time: "10:00 AM",
        modeOfPayment: "upi",
        feePeriod: "Dec 2024",
        studentUniqueId: "STU2024061",
        status: "approved",
        requestedBy: adminId,
      },
      {
        date: new Date("2024-12-12"),
        month: "December 2024",
        earnings: 12000,
        expenses: 0,
        description: "Winter hostel fee",
        type: "revenue",
        requestType: "hostel fee",
        name: "Winter Hostel Fee",
        time: "11:15 AM",
        modeOfPayment: "bank transfer",
        feePeriod: "Dec 2024",
        studentUniqueId: "STU2024062",
        status: "approved",
        requestedBy: adminId,
      },
      {
        date: new Date("2024-12-18"),
        month: "December 2024",
        earnings: 30000,
        expenses: 0,
        description: "Corporate donation for end-year",
        type: "revenue",
        requestType: "donation",
        name: "End Year Donation",
        time: "03:00 PM",
        modeOfPayment: "cheque",
        status: "approved",
        requestedBy: adminId,
      },
    ];

    const decemberExpenses = [
      {
        date: new Date("2024-12-01"),
        month: "December 2024",
        earnings: 0,
        expenses: 57000,
        description: "December staff salaries",
        type: "expense",
        requestType: "salary",
        name: "December Staff Salaries",
        time: "09:00 AM",
        modeOfPayment: "bank transfer",
        status: "approved",
        requestedBy: adminId,
        reviewedBy: adminId,
        reviewedAt: new Date("2024-12-01"),
      },
      {
        date: new Date("2024-12-10"),
        month: "December 2024",
        earnings: 0,
        expenses: 9500,
        description: "Winter supplies & clothing",
        type: "expense",
        requestType: "other",
        name: "Winter Supplies",
        time: "02:30 PM",
        modeOfPayment: "cash",
        status: "approved",
        requestedBy: adminId,
      },
      {
        date: new Date("2024-12-20"),
        month: "December 2024",
        earnings: 0,
        expenses: 20000,
        description: "Annual event arrangements",
        type: "expense",
        requestType: "other",
        name: "Annual Event Expense",
        time: "11:00 AM",
        modeOfPayment: "upi",
        status: "approved",
        requestedBy: adminId,
      },
    ];

    // ===== Mock old document you showed (keep as-is so demo contains it) =====
    const mockOldDoc = {
      // uses the exact date and createdBy style you pasted earlier
      date: new Date("2025-06-23T18:30:00.000Z"),
      month: "march",
      earnings: 0,
      expenses: 200,
      description: "cleaning labour ",
      createdBy: "admin@example.com",
      status: "approved",
    };

    // ===== Demo pending items (to test attachment deletion flow) =====
    // Note: make sure the files exist at these paths (or create placeholder files)
    const pendingDemoItems = [
      {
        date: new Date("2024-12-28"),
        month: "December 2024",
        earnings: 0,
        expenses: 2500,
        description: "Pending demo: vendor invoice (delete on approve)",
        type: "expense",
        requestType: "admin office",
        name: "Vendor Invoice Demo",
        time: "14:00",
        modeOfPayment: "upi",
        status: "pending",
        requestedBy: adminId,
        attachments: ["uploads/finance-requests/sample-bill.png"],
      },
      {
        date: new Date("2024-12-29"),
        month: "December 2024",
        earnings: 5000,
        expenses: 0,
        description: "Pending demo: tuition fee (delete on approve)",
        type: "revenue",
        requestType: "school fee",
        name: "Tuition Fee Demo",
        time: "11:00",
        modeOfPayment: "card",
        status: "pending",
        requestedBy: adminId,
        attachments: ["uploads/finance-requests/sample-invoice.png"],
      },
    ];

    // ===== Combine everything =====
    const allRevenue = [
      ...julyRevenue,
      ...augustRevenue,
      ...septemberRevenue,
      ...octoberRevenue,
      ...novemberRevenue,
      ...decemberRevenue,
    ];

    const allExpenses = [
      ...julyExpenses,
      ...augustExpenses,
      ...septemberExpenses,
      ...octoberExpenses,
      ...novemberExpenses,
      ...decemberExpenses,
    ];

    // Upsert all docs
    console.log("Seeding revenue records...");
    await upsertDocs(allRevenue);

    console.log("Seeding expense records...");
    await upsertDocs(allExpenses);

    console.log("Seeding demo pending items...");
    await upsertDocs(pendingDemoItems);

    console.log("Seeding mock old document...");
    await upsertDocs([mockOldDoc]);

    // Summary counts for sanity
    const totalSeeded = (await Earning.countDocuments({
      date: { $gte: new Date("2024-07-01"), $lte: new Date("2024-12-31") },
    })) || 0;

    const pendingCount = await Earning.countDocuments({ status: "pending" });

    console.log("Seeding finished.");
    console.log("Total records between Jul-Dec 2024:", totalSeeded);
    console.log("Total pending requests (all time):", pendingCount);

    await mongoose.disconnect();
    console.log("Disconnected from MongoDB. Done.");
    process.exit(0);
  } catch (error) {
    console.error("Seeding error:", error);
    try {
      await mongoose.disconnect();
    } catch (e) {}
    process.exit(1);
  }
};

seedFinanceData();
